// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt (args [0]); 
		int bigger = 0;
		int smaller = 0;
		for (int i=0; i<N; i++) {
			if (Math.random()>0.5) {
				bigger++;
			} else {
				smaller++;
			}
		}
		System.out.println ("> 0.5:  " + bigger + " times");
		System.out.println ("<= 0.5: " + smaller + " times");
		if ((smaller != 0)&&(bigger != 0)) {
			System.out.println("Ratio:  " + (double)bigger/smaller);
		}
	}
}
